apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: terminators.app.terminator.dev
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: app.terminator.dev
  names:
    kind: Terminator
    listKind: TerminatorList
    plural: terminators
    singular: terminator
  scope: Namespaced
  version: v1alpha1
